In [1]:
import numpy as np

In [3]:
# What is NumPy?
# NumPy (Numerical Python) is a Python library used for numerical and scientific computing.

# Why NumPy?
# Fast and memory-efficient
# Written in C, so it is much faster than Python Lists
# Used to create N-dimensional arrays
# Supports matrix operations, linear algebra and statistical calculations
# Widely used in Data Analysis, Machine Learning and Deep Learning
# Note: ML models usually expect data in a 2D format (rows × columns).

In [4]:
!pip install numpy  

  Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl (12.5 MB)


In [5]:
a= np.array([1,2,3,4])  #numpy can create array from list 
print(type(a))
print(a)
a.ndim #gives dimension of the array

<class 'numpy.ndarray'>
[1 2 3 4]


1

In [6]:
# List vs NumPy Array
# python list -- mixed datatype, slower, more memory, loop required, list of lists
# numpy array -- one data type, faster, less memory, vectorized,  1d 2d 3d

In [8]:
# mean method in np to display mean of array
a= np.array([121,456,234,789,987])
print(type(a))
print(np.mean(a))
print(a.ndim)

<class 'numpy.ndarray'>
517.4
1


In [10]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [11]:
b= np.array([[1,2,3,4],[5,6,7,8],[6,7,8,9]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [13]:
# slicing in array
# we want array [1,2/5,6]
# b[slice row, slice column]
b[0:2:1,0:2:1]

array([[1, 2],
       [5, 6]])

In [14]:
# slice array [2,4/7,9]
b[::2,1::2]

array([[2, 4],
       [7, 9]])

In [15]:
# slice array [2,3/6,7]
b[:2:,1:3:]

array([[2, 3],
       [6, 7]])

In [17]:
# slice array [6,7/7,8]
b[1::,1:3:]

array([[6, 7],
       [7, 8]])

In [18]:
#slice array [1,4/6,9]
b[::2,::3]

array([[1, 4],
       [6, 9]])

In [19]:
b[::-1,::]

array([[6, 7, 8, 9],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [20]:
b[::,::-1]

array([[4, 3, 2, 1],
       [8, 7, 6, 5],
       [9, 8, 7, 6]])

In [21]:
b[::-1,::-1]

array([[9, 8, 7, 6],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [22]:
# generating array from tuples
a= np.array(((1,2,3,4),(3,4,5,6),(8,9,7,6)))
a.ndim

2

In [23]:
# 3D Array
# 3D arrays are mainly used in:

# Image Processing
# Deep Learning
# Medical Imaging
# Video Processing

In [25]:
# array inside array inside array
a= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,5,8]]])
print(a.ndim)
print(a)
#here the array matix looks seperated on basis of depth

3
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 5 8]]]


In [26]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
a.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [29]:
# slicing in 3d array
# similar to 2d but first parameter is depth
a[0,:2:,:2:]

array([[1, 2],
       [4, 5]])

In [30]:
a[0,::2,::2]

array([[1, 3],
       [7, 9]])

In [31]:
# creating arrays with Data types

In [34]:
print(np.array([1,2,3],dtype=float))

[1. 2. 3.]


In [35]:
print(np.array([1,0,3],dtype=bool))

[ True False  True]


In [36]:
a= np.array([1,2,3,4,5,6,7,8,9,0])
a.size

10

In [38]:
a= np.array([[1,2,3,4],[5,6,7,8],[4,6,8,9]])
print(a.size) #gives total elements in array
print(a.shape) # gives the count of rows and columns in array
print(a) 

12
(3, 4)
[[1 2 3 4]
 [5 6 7 8]
 [4 6 8 9]]


In [40]:
# we can reshape the array as well into deifferent rows and columns 
# we have to just reshape in such a way that total numbers of elements remain constant
a.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4],
       [6, 8, 9]])

In [41]:
a.reshape(1,12)

array([[1, 2, 3, 4, 5, 6, 7, 8, 4, 6, 8, 9]])

In [42]:
a.reshape(12,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [4],
       [6],
       [8],
       [9]])

In [43]:
a.reshape(6,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [4, 6],
       [8, 9]])

In [44]:
a.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 4, 6, 8, 9]])

In [49]:
# arrange function is used to create sequential array
b= np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
c=np.arange(6,20,2)
c

array([ 6,  8, 10, 12, 14, 16, 18])

In [51]:
a=np.array([[2,5,7,8],[5,8,9,6],[2,8,9,4]])
a

array([[2, 5, 7, 8],
       [5, 8, 9, 6],
       [2, 8, 9, 4]])

In [52]:
np.transpose(a)

array([[2, 5, 2],
       [5, 8, 8],
       [7, 9, 9],
       [8, 6, 4]])

In [57]:
# coverting n dim array into 1 dim array using flatten function
a.flatten()

array([5, 7, 8, 3, 7, 9, 7, 8, 9])

In [55]:
a=np.array([[[5,7,8],[3,7,9],[7,8,9]]])
print(a.ndim)
print(a)

3
[[[5 7 8]
  [3 7 9]
  [7 8 9]]]


In [56]:
p= a.flatten()
print(p)

[5 7 8 3 7 9 7 8 9]


In [61]:
# creating a unit matrix using ones method
a= np.ones([4,3],dtype=np.int16) #int 16 tells that unit size of aech element will be 16bits ie 2 bytes
print(a)                         # int 32- 4 byte, int8- 1byte and so on

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [60]:
a.itemsize # gives size of each item

2

In [62]:
# creating a null matrix using zeros method
a=np.zeros([4,4],dtype=np.int8)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [66]:
#**np.linspace(): **
# to create a array with start , end , and iterval
# Generates numbers spaced evenly over a specified range.
a= np.linspace(10,20,5)
print(a)

[10.  12.5 15.  17.5 20. ]


In [71]:
#broadcasting : one op on every element without loop
#vectorization--avoiding loop
a=np.array([[1,2,3],[3,4,5],[4,5,6]])  
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [68]:
a*4

array([[ 4,  8, 12],
       [12, 16, 20],
       [16, 20, 24]])

In [70]:
# Broadcasting

# Real-life example: If every student's marks get +5 grace marks, NumPy adds 5 to every element automatically.

In [72]:
a+2

array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 8]])

In [73]:
# traditional way using lists 
# product of two list
a=[2,4,8]
b=[4,2,3]
c=[]
for i in range(len(a)):
  c.append(a[i]*b[i])
print(c)

[8, 8, 24]


In [74]:
# product of 2 arrays 
a=np.array([2,4,8])
b=np.array([4,2,3])
a*b
# hence the loop avoided , called vectorization

array([ 8,  8, 24])

In [75]:
# Vectorization
# Vectorization means performing operations on the entire array without writing explicit loops.

In [76]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [77]:
# Statistical Functions on array

In [81]:
a= np.array([1,2,3,4,5,6,7])
print(np.mean(a))    #prints avg of array
print(np.max(a))     #prints max of array
print(np.min(a))     #prints min of array
print(np.sum(a))     #prints sum of array

4.0
7
1
28
